---

- name: Include Operating System Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Install Dependencies
  yum:
    name: "{{ __oracle_client_dependencies | default([]) }}"
    state: installed

- name: Create the Oracle app base directory if it does not exist
  file:
    path: "{{ oracle_client_oracle_app_base }}"
    state: directory

- name: Creating Oracle Client Install Group
  group:
    state: present
    name: "{{ __oracle_client_group }}"
    gid: "{{ __oracle_client_group_id | default(omit) }}"

- name: Creating Oracle Client DBA Group
  group:
    state: present
    name: "{{ __oracle_client_dba_group }}"
    gid: "{{ __oracle_client_dba_group_id | default(omit) }}"

- name: Creating Oracle User
  user:
    state: present
    name: "{{ __oracle_client_user }}"
    uid: "{{ __oracle_client_user_id | default(omit) }}"
    group: "{{ __oracle_client_group }}"
    groups: "{{ __oracle_client_dba_group }}"
    home: "{{ oracle_client_user_home }}"

- name: Install Oracle Client
  include_tasks: install.yml
  when: oracle_client_install

- name: Run Configuration For Oracle
  include_tasks: configuration.yml
